name: Build - Clash Bot Event Streaming Service

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'

jobs:
  build-artifact:
    name: "Build Clash Bot Event Streaming Service"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle build
        run: |
          ls -lha
          CI=true ./gradlew clean build
